//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppCRUDSlim.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    
    public partial class TabUsuarios
    {
        public int IDUsuario { get; set; }
        [DisplayName("Nombre")]
        [StringLength(30, ErrorMessage = "La longitud máxima es de 30 caracteres")]
        public string NombreUsuario { get; set; }

        [DisplayName("Apellido Paterno")]
        [StringLength(20, ErrorMessage = "La longitud máxima es de 30 caracteres")]
        public string APaternoUsuario { get; set; }

        [DisplayName("Apellido Materno")]
        [StringLength(20, ErrorMessage ="La longitud máxima es de 30 caracteres")]
        public string AMaternoUsuario { get; set; }

        [DisplayName("E-Mail")]
        [EmailAddress(ErrorMessage ="Cuenta de Correo Inválida")]
        public string CorreoElectronico { get; set; }
    }
}
